####### README #######
### Необходимо в gitlab-ci.yml подставить нижеследующие variables ###
### Так как docker NotSSL уже Deprecated ############################
###  variables:
###    DOCKER_HOST: tcp://docker:2376
###    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA 
###    DOCKER_TLS_CERTDIR: "/certs"
###    DOCKER_TLS_VERIFY: 1
###    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
  - build

before_script:
  - export VAULT_ROLE_ID=${VAULT_ROLE_ID}
  - export VAULT_SECRET_ID=${VAULT_SECRET_ID}


stages:
  - deploy


deploy_sandbox:
  stage: deploy
  variables:
    DOCKER_HOST: tcp://docker:2376
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA 
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  image:
    name: git.click.uz:8443/click_promo/promov2/laravel:latest
    pull_policy: if-not-present
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\t StrictHostKeyChecking no \n\n" > ~/.ssh/config' 
    - ssh-keyscan 172.16.17.3 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA"  --env=sandbox --branch=master
  environment:
    name: sandbox
    url: https://dev-promo23.click.uz
  only:
    - master

deploy_prod:
  stage: deploy
  variables:
    DOCKER_HOST: tcp://docker:2376
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA 
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  image:
    name: git.click.uz:8443/click_promo/promov2/laravel:latest
    pull_policy: if-not-present
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\t StrictHostKeyChecking no \n\n" > ~/.ssh/config' 
    - ssh-keyscan 172.16.13.32 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA" --env=prod --branch=release
  environment:
    name: prod
    url: https://promov2.click.uz
  only:
    - release
  when: manual
